name: Build Executables

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libc6

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests bs4

    - name: Build Executable for Linux
      run: |
        pyinstaller --onefile --name="AnalyzerLoteryLinux" teste.py

    - name: Upload Linux Executable
      uses: actions/upload-artifact@v3
      with:
        name: linux-executable
        path: dist/AnalyzerLoteryLinux
