    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libc6

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests bs4

    - name: Build Executable
      run: |
        pyinstaller --onefile --name="AnalyzerLoteryLinux" teste.py
